spring.datasource.url=jdbc:postgresql://localhost:5432/easy_bank_db
spring.datasource.username=postgres
spring.datasource.password=postgres_password

spring.security.user.name=user
spring.security.user.password=user

spring.jpa.hibernate.ddl-auto=validate